/******************************************************
 * This file is generated by RPUCompiler automatically.
 * ----------------------------------------------------
 */


#ifndef MAT_MUL_NODE_2_CL0_H
#define MAT_MUL_NODE_2_CL0_H


#define MAT_MUL_NODE_2_LOAD_BASE		0
#define MAT_MUL_NODE_2_STORE_BASE		2048


#define MAT_MUL_NODE_2_CL0_SIZE	5

unsigned int mat_mul_NODE_2_cl0_ctx [] = {
		0x00000000,
		0x00000000,
		0x00000040,
		0x00000800,
		0x00000040
};

#endif
