/******************************************************
 * This file is generated by RPUCompiler automatically.
 * ----------------------------------------------------
 * This file include CL1 context to initialize GCGM. 
 */

#ifndef MAT_MUL_NODE_2_CL1_H
#define MAT_MUL_NODE_2_CL1_H


#define MAT_MUL_NODE_2_CL1_SIZE	1;


#define MAT_MUL_NODE_2_CL1_0_SIZE	21;

unsigned int mat_mul_NODE_2_CL1_ctx_0 [] = {
		0x00001540,
		0x40000000,
		0x00000000,
		0x00000000,
		0x0003e018,
		0xc0000001,
		0x00000000,
		0x10000390,
		0x0003e400,
		0x80000002,
		0x00000000,
		0x10000380,
		0x0003c000,
		0x80000003,
		0x00000000,
		0x1031f380,
		0x00040000,
		0x80000004,
		0x00000000,
		0x1021f380,
		0x00040000
};


#endif
